<a href="https://colab.research.google.com/github/Parishri07/Learning-PyTorch/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.3.0+cu121


**Introduction to sensors**

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8], [8,10]])
MATRIX

tensor([[ 7,  8],
        [ 8, 10]])

In [ ]:
# TENSORS
TENSORS = torch.tensor([[[7,8], [8,10], [1,2]]])
TENSORS

tensor([[[ 7,  8],
         [ 8, 10],
         [ 1,  2]]])

Random tensors

start with random numbers and modify acc to data

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0742, 0.1140, 0.3426, 0.1493],
        [0.9957, 0.9388, 0.2117, 0.4799],
        [0.7595, 0.8966, 0.4765, 0.2590]])

In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
x_permuted = random_image_size_tensor.permute(1,2,0)
x_permuted.shape, x_permuted.ndim

(torch.Size([224, 224, 3]), 3)

**NumPy and PyTorch Tensor**

NumPy to PyTorch tensor -> torch.from_numpy(ndarray)

PyTorch tensor to NumPy -> torch.Tensor.numpy()

**Reproducibilty**

Random seed: to reduce the randomness in nueral network

In [2]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A == random_tensor_B)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
